// One entry per product page that existed before the catalogue rebuild, sending
// it to the product that replaced it. Google has these addresses indexed and
// buyers have them saved in WhatsApp threads, so without this they 404.
// Generated by matching the old catalogue's photos to the new ones.
const productRedirects = require('./src/data/product-redirects.json');

/** @type {import('next').NextConfig} */
const nextConfig = {
  // The parent folder has its own package-lock.json, so Next guesses the
  // workspace root is one level up. Pin it to this app instead — otherwise file
  // tracing walks the whole `Crosswild ` folder (including the image archives).
  outputFileTracingRoot: __dirname,
  reactStrictMode: false,
  async redirects() {
    return [
      // ── Page renames ──
      // /services now has its own page — no redirect needed
      { source: '/gallery',        destination: '/image-gallery', permanent: true },
      { source: '/our-process',    destination: '/our_process',   permanent: true },
      // Typo fix: old URL was /desclaimer — now /disclaimer (308 permanent redirect)
      { source: '/desclaimer',     destination: '/disclaimer',    permanent: true },
      // ── Case-sensitivity fixes (old site used uppercase letters in slugs) ──
      // These live in src/middleware.ts, not here. `source` matching is
      // case-insensitive, so a rule sending /...-in-Kota to /...-in-kota also
      // matched the lowercase target and redirected it to itself — both Kota
      // pages and /bags-manufacturer-in-jodhpur served an infinite 308 loop and
      // could not be crawled at all. The middleware compares the path exactly,
      // so only the capitalised spelling is redirected.

      // ── Blog posts whose old-site URL differs from the slug in the CMS ──
      // Both are indexed under the old address; the post itself is unchanged.
      { source: '/blog/sustainable-fabrics-for-promotional-clothing', destination: '/blog/sustainable-material-in-custom-promotional-apparel', permanent: true },
      { source: '/blog/custom-t-shirts-for-promotional-events',       destination: '/blog/custom-tshirt-manufacturer-promotional-events',       permanent: true },
      // ── Clean URL migration ──
      // Old plural /categories/<slug> → new singular /category/<slug>
      // Legacy /products?category=X&sub=Y is handled in src/middleware.ts so
      // the orphan query string gets stripped instead of carried over.
      { source: '/categories/:slug',  destination: '/category/:slug', permanent: true },

      // ── Catalogue rebuild: old product pages → their replacements ──
      // Last, so every specific rule above still wins.
      ...productRedirects,
    ];
  },

  async rewrites() {
    const backendUrl = process.env.BACKEND_URL || 'https://crosswild-backend-p5l3.onrender.com';

    // Location SEO pages — served without /locations/ prefix (matches production URLs)
    const locationSlugs = [
      'tshirt-manufacturer-in-jodhpur',
      'bags-manufacturer-in-jodhpur',
      'cap-printing-manufacturer-jodhpur',
      'uniform-manufacturer-jodhpur',
      'tshirt-manufacturer-in-indore',
      'bag-manufacturer-in-indore',
      'uniform-manufacturer-in-indore',
      'bags-manufacturing-company-in-udaipur',
      'tshirt-manufacturer-wholesaler-in-udaipur',
      'tshirt-manufacturer-wholesaler-in-kota',
      'bags-manufacturing-company-in-kota',
      'tshirt-manufacturer-wholesaler-in-sikar',
      'bags-manufacturing-company-in-sikar',
    ];

    return [
      { source: '/api/:path*', destination: `${backendUrl}/api/:path*` },
      ...locationSlugs.map((slug) => ({
        source: `/${slug}`,
        destination: `/locations/${slug}`,
      })),
    ];
  },
  async headers() {
    return [
      {
        // Security headers for all routes
        source: '/(.*)',
        headers: [
          { key: 'X-DNS-Prefetch-Control', value: 'on' },
          { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
        ],
      },
      {
        // Cache static images
        source: '/images/(.*)',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
      {
        // Cache Next.js static assets
        source: '/_next/static/(.*)',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
    ];
  },
  images: {
    // Vercel's image optimizer is served from a metered quota, and once that
    // quota is exhausted EVERY /_next/image request answers 402 — the whole
    // site loses its images at once, including the header logo and the product
    // photos, with nothing in the code to show for it. Serving the files
    // directly removes that single point of failure. The source images were
    // compressed to suit (26.3MB -> 5.2MB across public/), so the pages stay
    // light without the optimizer in front of them.
    //
    // remotePatterns below is left in place: it is ignored while unoptimized
    // is set, and is exactly what would be needed to switch back.
    unoptimized: true,
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
        port: "",
      },
      {
        protocol: "https",
        hostname: "via.placeholder.com",
      },
      {
        protocol: "https",
        hostname: "i.ibb.co",
      },
      {
        protocol: "https",
        hostname: "**.ibb.co",
      },
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
      },
      {
        // Cloudflare R2 — where the backend uploads images (STORAGE_DRIVER=r2).
        // Matches R2_PUBLIC_BASE in the backend env; pinned to this bucket rather
        // than **.r2.dev so the image optimizer can't be pointed at other buckets.
        protocol: "https",
        hostname: "pub-e632e16b74374ce8bb6fc4f36b6e36a7.r2.dev",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
      {
        protocol: "https",
        hostname: "www.thecrosswild.com",
      },
      {
        protocol: "https",
        hostname: "thecrosswild.com",
      },
    ],
  },
  eslint: {
    // Warning: This allows production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true,
  },
};

module.exports = nextConfig;
